import type { NextApiRequest, NextApiResponse } from 'next';
import { SITE_URL } from '@/lib/constants';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const robotsTxt = `# robots.txt for ${SITE_URL}
# Generated by Frezya Website

User-agent: *
Allow: /

# Sitemap location
Sitemap: ${SITE_URL}/api/sitemap.xml

# Disallow admin and API routes
Disallow: /admin
Disallow: /api/

# Allow specific API routes for SEO
Allow: /api/sitemap.xml
Allow: /api/robots.txt
`;

  res.setHeader('Content-Type', 'text/plain');
  res.setHeader('Cache-Control', 'public, s-maxage=86400, stale-while-revalidate');
  res.status(200).send(robotsTxt);
}
